title = 'seraldinho.github.io'


[params]
  showAppearanceSwitcher = false        # Blowfish theme param
  colorScheme = "avocado"                 # Blowfish color scheme
  defaultAppearance = "dark"            # Blowfish light/dark mode default
  autoSwitchAppearance = false          # Blowfish auto‑switch appearance
  mainSections = ["writeups", "mates"]

  [params.author]
    name = "Nicolás Seral"
    email = "nseral@proton.me"
    image = "img/pinguino3.png"
    headline = "writeups, notas y demás."
    bio = "bla bla bla bla"
    links = [
      { email = "nseral@proton.me" },
      { github = "https://github.com/seraldinho" },
      { hackthebox = "https://app.hackthebox.com/users/1297012"}
    ]


  [params.homepage]
    layout = "background"
    showRecent = true
    layoutBackgroundBlur = true
    homepageImage = "/img/wallpaper.png"
    showRecentItems = 6
    showMoreLink = false
    # showMoreLinkDest = "/posts/"
    cardView = false
    cardViewScreenWidth = false
    disableHeroImageFilter = false
