[[main]]
  name = "Writeups"
  pre = "code"
  pageRef = "writeups"
  weight = 10

[[main]]
    name = "Easy"
    parent = "Writeups"
    pageRef = "tags/easy"
    weight = 10

[[main]]
    name = "Medium"
    parent = "Writeups"
    pageRef = "tags/medium"
    weight = 20

[[main]]
    name = "Hard"
    parent = "Writeups"
    pageRef = "tags/hard"
    weight = 30

[[main]]
  name = "Notas"
  pre = "pencil"
  pageRef = "notas"
  weight = 20

[[main]]
    name = "Protocolos"
    parent = "Notas"
    pageRef = "protocolos"
    weight = 10

[[main]]
    name = "Técnicas"
    parent = "Notas"
    pageRef = "tecnicas"
    weight = 20

[[main]]
    name = "Tags"
    pre = "firma"
    pageRef = "tags"
    weight = 30
